### ISSUE TITLE
Maybe an error in warps.py

### ISSUE THREAD

**Issue by ConvolutedDog** [NMSU-PEARL/PPT-GPU#2]
There maybe an error in [https://github.com/NMSU-PEARL/PPT-GPU/blob/0351db7b62007aed0752900eee98b3a2e4f753b0/src/warps.py#L66](url).

When I simulate the cublas benchmark, I encountered this bug:
```shell
Traceback (most recent call last):
  File "ppt.py", line 330, in <module>
    main()
  File "ppt.py", line 307, in main
    simianEngine.run()
  File "/home/xxx/Github/PPT-GPU/simian.py", line 1730, in run
    service(event["data"], event["tx"], event["txId"]) #Receive TO BE CGECJED
  File "/home/xxx/Github/PPT-GPU/src/kernels.py", line 290, in kernel_call
    instructions_executed = self.warp_scheduler.step(current_warp_list, pred_out["active_cycles"]) 
  File "/home/xxx/Github/PPT-GPU/src/warp_scheduler.py", line 33, in step
    return self.step_LRR(warp_list, cycles)
  File "/home/xxx/Github/PPT-GPU/src/warp_scheduler.py", line 55, in step_LRR
    current_inst_executed = warp.step(cycles)
  File "/home/xxx/Github/PPT-GPU/src/warps.py", line 50, in step
    if self.process_inst(cycles):
  File "/home/xxx/Github/PPT-GPU/src/warps.py", line 69, in process_inst
    inst = self.tasklist[self.current_inst]
IndexError: list index out of range

```

Maybe this line should use **`>=`** like:
```python
elif self.current_inst >= len(self.tasklist):
```

All traces and other files that needed to reproduce this bug have been uploaded in the next comment.

**Comment by ConvolutedDog** [comment]
The `sass_traces`, `memory_traces`, `app_config.py` and `QV100.py` are in the attachment.

[traces_and_others.zip](https://github.com/NMSU-PEARL/PPT-GPU/files/13200964/traces_and_others.zip)

And the simulation command is:
```shell
mpiexec -n 10 python3 ppt.py --app ./traces_and_others --sass --config QV100 --granularity 1
```
